# Generated by Django 5.2.1 on 2025-12-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reco_backend_app', '0003_friendship'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookreview',
            table='user_books',
        ),
        migrations.AlterModelTable(
            name='contentreview',
            table='reviews',
        ),
    ]
