# Generated by Django 5.2.7 on 2025-12-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco_backend_app', '0003_contentreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentreview',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
